
#
# These are the flags that build the project.
CC			= $(CXX)
CXXFLAGS	= -std=c++20

NisseV1:	NisseV1.o HTTPStuff.o


#
# These are targets that my NeoVim plugins use for syntax highlighting.
neovimflags:
	@echo $(CXXFLAGS)


