
#
# These are the flags that build the project.
CPPFLAGS	= -I/opt/homebrew/include
CXXFLAGS	= -std=c++20
LDFLAGS		= -L/opt/homebrew/lib
LDLIBS		= -lThorsLogging -lThorsSocket

NisseV2:


#
# These are targets that my NeoVim plugins use to syntax highlighting.
neovimflags:
	@echo $(CPPFLAGS) $(CXXFLAGS)


